name: github_testing_actions_lab2
on:
  pull_requests:
    branches:
      - main
jobs:
  lab2-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Install dependencies
        working-directory: lab_2/lab2
        run: |
          pwd
          python -m pip install --upgrade pip
          curl -sSL https://install.python-poetry.org | python -
          poetry install
      - name: Run Pytest
        working-directory: lab_2/lab2
        run: poetry run pytest tests
