name: github_testing_actions
on:
  push:
    branches:
      - main
jobs:
  lab2-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: setting up virtual environment
        run: |
          python3 -m pip install --upgrade pip
          curl -sSL https://install.python-poetry.org | python3 -
      - name: set up poetry
        working-directory: ./lab_2/lab2
        run: |
          pwd
          poetry --version
          poetry install

      - name: Pytest
        working-directory: ./lab_2/lab2
        run: |
          pwd
          poetry run pytest tests
